version: "3"
services:
  node:
    volumes:
      - project_src:/home/node/app:delegated

volumes:
  project_src:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"
